/*
 * generated by Xtext 2.32.0
 */
package exp.engine.dsl.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class ExpLangProposalProvider extends AbstractExpLangProposalProvider {
}
