/*
 * generated by Xtext 2.32.0
 */
package exp.engine.dsl.ide

import com.google.inject.Guice
import exp.engine.dsl.ExpLangRuntimeModule
import exp.engine.dsl.ExpLangStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class ExpLangIdeSetup extends ExpLangStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new ExpLangRuntimeModule, new ExpLangIdeModule))
	}
	
}
