/*
 * generated by Xtext 2.32.0
 */
package exp.engine.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ExpLangRuntimeModule extends AbstractExpLangRuntimeModule {
}
