/*
 * generated by Xtext 2.32.0
 */
package exp.engine.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ExpLangStandaloneSetup extends ExpLangStandaloneSetupGenerated {

	def static void doSetup() {
		new ExpLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
